export const TRANSLATIONS = {
  zh: {
    pageTitle: 'SearchAIO — 多站点搜索', searchLabel: '搜索内容', searchPlaceholder: '输入内容，或使用 google: 查询、!g 查询',
    search: '搜索', lucky: '手气不错', copyLink: '生成教程链接（复制）', directShare: '直接分享', switchEngine: '切换搜索引擎', enginePanelEyebrow: '搜索目的地', enginePanelTitle: '选择搜索引擎',
    tutorialEyebrow: '我帮你搜索', tutorialTitle: '生成可分享的教学链接', tutorialDescription: '链接会按当前搜索引擎的搜索舞台输入内容，再跳转到对应网站。',
    groupWeb: '网页搜索', groupSpecialized: '垂直 / 学术 / 医疗', groupAi: 'AI 对话', groupFavorites: '已收藏', favoriteAdd: '收藏此引擎', favoriteRemove: '取消收藏',
    catalogEyebrow: '完整目录', catalogTitle: '全部搜索引擎', catalogSearchLabel: '筛选搜索引擎', catalogSearchPlaceholder: '搜索名称、前缀或 !bang', catalogOpen: '全部 {{count}} 个', catalogEmpty: '没有匹配的搜索引擎。',
    footerPrivacy: '偏好设置只保存在此浏览器中。', shortcutsTitle: '键盘快捷键', shortcutRoute: '{{prefix}}: / !{{bang}}', shortcutFocus: '聚焦搜索框', shortcutCycle: '切换搜索引擎', shortcutBangExample: 'g 查询', shortcutBang: '用 !bang 路由搜索', shortcutClose: '关闭建议或弹窗',
    routeHint: '当前：{{engine}}（{{mode}}）。可输入 {{prefix}}: 或 !{{bang}} 直接切换。', emptyQuery: '请输入要搜索的内容。', selectedEngine: '已切换到 {{engine}}。',
    copied: '教学链接已复制。', shared: '已打开系统分享。', shareFailed: '系统分享失败，请使用复制按钮。', copyFailed: '无法自动复制，请手动复制链接：', popupBlocked: '浏览器阻止了新标签页，请允许弹窗后重试。', registryError: '搜索引擎配置检查失败：{{details}}', promptCopied: '提示词已复制；目标页面打开后直接粘贴即可。', promptCopyFailed: '已打开目标页面；请手动复制原搜索内容。', engineRetired: '{{engine}} 已停服，保留在索引中供历史查阅，无法继续搜索。', enginePending: '{{engine}} 尚待登录验证，暂不提供搜索。', statusPending: '待定',
    modeSearch: '网页搜索', modeAiSearch: 'AI 直达', modePrompt: '复制提示词', modeRetired: '已停服',
    engineGoogle: '通用网页搜索；保留经典、居中的搜索舞台和真实的“手气不错”跳转。', engineGoogleAi: '尝试进入 Google AI Mode；使用 udm=50 参数，但可用性受地区、账号与 Google 重定向影响。', engineBing: '微软网页搜索，使用更冷静的蓝绿色品牌舞台。', engineBaidu: '面向中文内容的网页搜索。', engineYandex: '适合俄语与跨区域内容的网页搜索。', engineYahoo: '新闻、财经和门户型内容搜索。', engineSogou: '中文社交与网页内容搜索。', engine360: '面向中文网页的搜索入口。', engineDuckDuckGo: '以隐私导向著称的网页搜索。', engineBrave: '独立索引和隐私导向的网页搜索。', engineChatGPT: '复制提示词后打开 ChatGPT；避免未登录时丢弃查询参数。', engineCopilot: '复制提示词后打开 Copilot；其当前页面会清除查询参数。', engineCelia: '华为 Celia 智能助手入口。', engineQuark: '夸克当前是带有 AI 能力的网页搜索结果页，归入网页搜索。', enginePerplexity: '以来源和研究问答著称的 AI 搜索。', engineYou: 'You.com 的 AI 与搜索入口。', engineYouTube: '视频搜索入口。', engineScholar: '学术文献搜索入口。', engineImages: '图片搜索入口。', engineWikipedia: '百科知识搜索入口。', engineGitHub: '开源仓库与代码搜索入口。', engineStackOverflow: '编程问答搜索入口。', engineArxiv: '预印本论文搜索入口。', enginePubMed: '生物医学论文搜索入口。', engineGemini: 'Gemini 采用复制提示词后打开主页的可靠方式。', engineClaude: 'Claude 目前采用复制提示词后打开新对话的可靠方式。', engineGrok: 'Grok AI 对话入口。', engineDeepSeek: 'DeepSeek 采用复制提示词后打开主页的可靠方式。', engineQwen: '通义千问采用复制提示词后打开主页的可靠方式。', engineDoubao: '豆包采用复制提示词后打开新对话的可靠方式。', engineGenericDescription: '{{engine}}：来自 {{category}} 目录的补充入口。'
  },
  en: {
    pageTitle: 'SearchAIO — Multi-site search', searchLabel: 'Search query', searchPlaceholder: 'Search, or route with google: query / !g query',
    search: 'Search', lucky: "I'm Feeling Lucky", copyLink: 'Create tutorial link (copy)', directShare: 'Share directly', switchEngine: 'Switch search engine', enginePanelEyebrow: 'Search destination', enginePanelTitle: 'Choose an engine',
    tutorialEyebrow: 'Let me search for you', tutorialTitle: 'Create a shareable tutorial link', tutorialDescription: 'The link types into the selected search stage, then opens the destination service.',
    groupWeb: 'Web search', groupSpecialized: 'Specialized, academic & health', groupAi: 'AI chat', groupFavorites: 'Favorites', favoriteAdd: 'Add favorite', favoriteRemove: 'Remove favorite',
    catalogEyebrow: 'Full catalog', catalogTitle: 'All search engines', catalogSearchLabel: 'Filter search engines', catalogSearchPlaceholder: 'Search by name, prefix, or !bang', catalogOpen: 'All {{count}}', catalogEmpty: 'No search engines match.',
    footerPrivacy: 'Preferences stay in this browser only.', shortcutsTitle: 'Keyboard shortcuts', shortcutRoute: '{{prefix}}: / !{{bang}}', shortcutFocus: 'Focus search', shortcutCycle: 'Change engine', shortcutBangExample: 'g query', shortcutBang: 'Route with a !bang', shortcutClose: 'Close suggestions or dialog',
    routeHint: 'Current: {{engine}} ({{mode}}). Type {{prefix}}: or !{{bang}} to route directly.', emptyQuery: 'Enter something to search.', selectedEngine: 'Switched to {{engine}}.',
    copied: 'Tutorial link copied.', shared: 'System share opened.', shareFailed: 'System sharing failed. Use the copy button instead.', copyFailed: 'Could not copy automatically. Copy this link:', popupBlocked: 'Your browser blocked the new tab. Allow popups and try again.', registryError: 'Engine registry check failed: {{details}}', promptCopied: 'Prompt copied. Paste it into the destination page.', promptCopyFailed: 'The destination page opened. Copy the original query manually.', engineRetired: '{{engine}} has shut down. It remains indexed for historical reference and cannot run a search.', enginePending: '{{engine}} is pending sign-in verification and is not available for search yet.', statusPending: 'pending',
    modeSearch: 'web search', modeAiSearch: 'AI direct', modePrompt: 'copy prompt', modeRetired: 'retired',
    engineGoogle: 'General web search with a classic centered search stage and a real lucky redirect.', engineGoogleAi: 'Attempts Google AI Mode with udm=50; availability depends on region, account, and Google redirects.', engineBing: 'Microsoft web search with a cool blue-green search stage.', engineBaidu: 'Web search for Chinese-language content.', engineYandex: 'Web search for Russian and cross-region content.', engineYahoo: 'News, finance, and portal-oriented search.', engineSogou: 'Chinese social and web content search.', engine360: 'A Chinese web search destination.', engineDuckDuckGo: 'A privacy-oriented web search destination.', engineBrave: 'An independent-index, privacy-oriented web search destination.', engineChatGPT: 'Opens ChatGPT after copying the prompt, avoiding dropped query parameters when signed out.', engineCopilot: 'Opens Copilot after copying the prompt because its current page clears query parameters.', engineCelia: 'Huawei Celia assistant entry.', engineQuark: 'A web-results experience with AI features; classified as web search.', enginePerplexity: 'An AI answer engine focused on sourced research.', engineYou: 'You.com AI and search entry.', engineYouTube: 'Video search.', engineScholar: 'Academic literature search.', engineImages: 'Image search.', engineWikipedia: 'Encyclopedic knowledge search.', engineGitHub: 'Open-source repositories and code search.', engineStackOverflow: 'Programming Q&A search.', engineArxiv: 'Preprint research search.', enginePubMed: 'Biomedical literature search.', engineGemini: 'Gemini opens after copying the prompt.', engineClaude: 'Claude opens a new chat after copying the prompt.', engineGrok: 'Grok AI conversation entry.', engineDeepSeek: 'DeepSeek opens after copying the prompt.', engineQwen: 'Qwen opens after copying the prompt.', engineDoubao: 'Doubao opens a new chat after copying the prompt.', engineGenericDescription: '{{engine}} is an additional {{category}} destination.'
  },
  ru: {
    pageTitle: 'SearchAIO — поиск по сайтам', searchLabel: 'Поисковый запрос', searchPlaceholder: 'Введите запрос или google: запрос / !g запрос',
    search: 'Поиск', lucky: 'Мне повезёт', copyLink: 'Создать обучающую ссылку (копировать)', directShare: 'Поделиться напрямую', switchEngine: 'Сменить поисковый движок', enginePanelEyebrow: 'Назначение поиска', enginePanelTitle: 'Выберите движок',
    tutorialEyebrow: 'Я помогу найти', tutorialTitle: 'Создать обучающую ссылку', tutorialDescription: 'Ссылка вводит запрос в выбранную поисковую сцену и открывает целевой сервис.',
    groupWeb: 'Веб-поиск', groupSpecialized: 'Спец., академический и мед.', groupAi: 'AI-чаты', groupFavorites: 'Избранное', favoriteAdd: 'Добавить в избранное', favoriteRemove: 'Убрать из избранного',
    catalogEyebrow: 'Полный каталог', catalogTitle: 'Все поисковые движки', catalogSearchLabel: 'Фильтр поисковых движков', catalogSearchPlaceholder: 'Имя, префикс или !bang', catalogOpen: 'Все {{count}}', catalogEmpty: 'Нет подходящих движков.',
    footerPrivacy: 'Настройки хранятся только в этом браузере.', shortcutsTitle: 'Горячие клавиши', shortcutRoute: '{{prefix}}: / !{{bang}}', shortcutFocus: 'Фокус поиска', shortcutCycle: 'Сменить движок', shortcutBangExample: 'g запрос', shortcutBang: 'Маршрут через !bang', shortcutClose: 'Закрыть подсказки или окно',
    routeHint: 'Текущий: {{engine}} ({{mode}}). Введите {{prefix}}: или !{{bang}} для маршрута.', emptyQuery: 'Введите поисковый запрос.', selectedEngine: 'Выбран {{engine}}.',
    copied: 'Обучающая ссылка скопирована.', shared: 'Открыто системное меню отправки.', shareFailed: 'Системная отправка не удалась. Используйте кнопку копирования.', copyFailed: 'Автокопирование не удалось. Скопируйте ссылку:', popupBlocked: 'Браузер заблокировал новую вкладку. Разрешите всплывающие окна и повторите.', registryError: 'Ошибка проверки движков: {{details}}', promptCopied: 'Запрос скопирован. Вставьте его на целевой странице.', promptCopyFailed: 'Целевая страница открыта. Скопируйте исходный запрос вручную.', engineRetired: '{{engine}} закрыт. Запись сохранена для истории и не может выполнить поиск.', enginePending: '{{engine}} ожидает проверки входа и пока недоступен для поиска.', statusPending: 'ожидает',
    modeSearch: 'веб-поиск', modeAiSearch: 'AI напрямую', modePrompt: 'копировать запрос', modeRetired: 'закрыт',
    engineGoogle: 'Универсальный веб-поиск с классической центральной поисковой сценой.', engineGoogleAi: 'Пытается открыть Google AI Mode через udm=50; доступность зависит от региона, аккаунта и редиректов Google.', engineBing: 'Веб-поиск Microsoft в сине-зелёной теме.', engineBaidu: 'Поиск китайского веб-контента.', engineYandex: 'Поиск русскоязычного и регионального контента.', engineYahoo: 'Поиск новостей, финансов и портального контента.', engineSogou: 'Поиск китайского социального и веб-контента.', engine360: 'Китайский веб-поисковый сервис.', engineDuckDuckGo: 'Веб-поиск с акцентом на приватность.', engineBrave: 'Независимый приватный веб-поиск.', engineChatGPT: 'ChatGPT открывается после копирования запроса; это исключает потерю параметра без входа.', engineCopilot: 'Copilot открывается после копирования запроса, поскольку текущая страница очищает параметр запроса.', engineCelia: 'Вход в ассистент Huawei Celia.', engineQuark: 'Веб-поиск с AI-функциями.', enginePerplexity: 'AI-ответы с фокусом на источники.', engineYou: 'Вход в You.com AI и поиск.', engineYouTube: 'Поиск видео.', engineScholar: 'Поиск научной литературы.', engineImages: 'Поиск изображений.', engineWikipedia: 'Энциклопедический поиск.', engineGitHub: 'Поиск репозиториев и кода.', engineStackOverflow: 'Поиск программных ответов.', engineArxiv: 'Поиск препринтов.', enginePubMed: 'Поиск биомедицинской литературы.', engineGemini: 'Gemini открывается после копирования запроса.', engineClaude: 'Claude открывает новый чат после копирования запроса.', engineGrok: 'Вход в Grok AI.', engineDeepSeek: 'DeepSeek открывается после копирования запроса.', engineQwen: '通义千问 открывает новый чат после копирования запроса.', engineDoubao: '豆包 открывает новый чат после копирования запроса.', engineGenericDescription: '{{engine}} — дополнительный пункт категории {{category}}.'
  }
};

export function translate(language, key, values = {}) {
  const dictionary = TRANSLATIONS[language] || TRANSLATIONS.en;
  return (dictionary[key] || TRANSLATIONS.en[key] || key).replace(/\{\{(\w+)\}\}/g, (_, name) => values[name] ?? '');
}
