import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = path.join(root, 'src', 'main.js');
const output = path.join(root, 'src', 'main.standalone.js');
const visited = new Set();
const chunks = [];

async function bundle(file) {
  const absolute = path.resolve(path.dirname(file), file);
  if (visited.has(absolute)) return;
  visited.add(absolute);
  let source = await fs.readFile(absolute, 'utf8');
  const imports = [...source.matchAll(/^import\s+\{[^}]+\}\s+from\s+['"](.+?)['"];?\s*$/gm)];
  for (const match of imports) {
    await bundle(path.resolve(path.dirname(absolute), match[1]));
  }
  source = source
    .replace(/^import\s+\{[^}]+\}\s+from\s+['"](.+?)['"];?\s*$/gm, '')
    .replace(/\bexport\s+(?=(?:const|function|async\s+function|class)\b)/g, '');
  chunks.push(`\n/* ${path.relative(root, absolute).replaceAll('\\', '/')} */\n${source}`);
}

await bundle(entry);
const outputSource = `/* Generated by tools/build-static.mjs. Edit src/*.js, then run npm run build:static. */\n(() => {\n'use strict';\n${chunks.join('\n')}\n})();\n`;
await fs.writeFile(output, outputSource, 'utf8');
console.log(`Wrote ${path.relative(root, output)} (${outputSource.length} bytes)`);
